# Doc-Repo-Manager Agent Configuration
# Manages documentation storage and repository operations

agent:
  name: doc-repo-manager
  version: 1.0.0
  description: Handles GitHub repository operations for documentation storage and version control
  type: storage_specialist

capabilities:
  - repository_management
  - version_control
  - branch_operations
  - pull_request_management
  - documentation_indexing
  - search_optimization

responsibilities:
  - Manage documentation repository structure
  - Handle Git operations for documentation
  - Create and manage branches
  - Generate pull requests
  - Maintain documentation index
  - Implement search functionality
  - Manage documentation metadata

operations:
  store_documentation:
    description: Store documentation in repository
    steps:
      - validate_documentation
      - determine_location
      - create_branch
      - commit_files
      - create_pull_request

  retrieve_documentation:
    description: Retrieve specific documentation
    steps:
      - parse_request
      - locate_documentation
      - fetch_content
      - return_formatted

  index_documentation:
    description: Build searchable index
    steps:
      - scan_repository
      - extract_metadata
      - build_index
      - update_search_cache

  manage_versions:
    description: Handle documentation versioning
    steps:
      - tag_versions
      - maintain_changelog
      - archive_old_versions

git_operations:
  branch_naming:
    pattern: "docs/{type}/{name}-{timestamp}"
    types:
      - feature
      - update
      - fix
      - refactor

  commit_messages:
    format: "docs({scope}): {description}"
    examples:
      - "docs(api): Add endpoint documentation"
      - "docs(architecture): Update system design"
      - "docs(readme): Fix installation steps"

  pull_request:
    template: |
      ## Documentation Update

      ### Summary
      {summary}

      ### Changes
      {changes}

      ### Checklist
      - [ ] Follows style guide
      - [ ] Links validated
      - [ ] Examples tested
      - [ ] Reviewed by technical writer

repository_structure:
  organization:
    by_project: true
    by_type: true
    hierarchical: true

  metadata:
    required_fields:
      - title
      - description
      - last_updated
      - author
      - tags
      - status

  indexing:
    fields:
      - title
      - content
      - tags
      - project
      - type
      - last_modified

search_configuration:
  engine: elasticsearch
  features:
    - full_text_search
    - fuzzy_matching
    - faceted_search
    - relevance_ranking

  optimization:
    - content_extraction
    - keyword_indexing
    - synonym_mapping
    - stemming

automation:
  scheduled_tasks:
    index_rebuild:
      frequency: daily
      time: "02:00"

    link_validation:
      frequency: weekly
      day: sunday

    backup:
      frequency: daily
      retention: 30

  hooks:
    pre_commit:
      - validate_markdown
      - check_links
      - verify_metadata

    post_merge:
      - update_index
      - notify_subscribers
      - trigger_deployment

integration:
  github:
    api_version: v3
    authentication: token
    permissions:
      - repo
      - write
      - pull_request

  external_tools:
    - markdown_linter
    - link_checker
    - search_indexer

error_handling:
  conflict_resolution:
    strategy: merge_with_review
    auto_resolve: false

  validation_failures:
    block_merge: true
    notify_author: true

monitoring:
  track:
    - repository_size
    - documentation_count
    - search_queries
    - index_performance
    - pr_merge_time

  alerts:
    - repository_quota_warning
    - index_failure
    - merge_conflicts
    - validation_errors